<HTML>
<HEAD>
<meta charset="UTF-8">
<title>Failure.cause - vertx</title>
<link rel="stylesheet" href="../../../style.css">
</HEAD>
<BODY>
<a href="../../index.html">vertx</a>&nbsp;/&nbsp;<a href="../index.html">io.vertx.ext.unit.report</a>&nbsp;/&nbsp;<a href="index.html">Failure</a>&nbsp;/&nbsp;<a href=".">cause</a><br/>
<br/>
<h1>cause</h1>
<a name="io.vertx.ext.unit.report.Failure$cause()"></a>
<code><span class="keyword">abstract</span> <span class="keyword">fun </span><span class="identifier">cause</span><span class="symbol">(</span><span class="symbol">)</span><span class="symbol">: </span><a href="https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-throwable/index.html"><span class="identifier">Throwable</span></a></code>
<p><strong>Return</strong><br/>
the underlying exception causing this failure, it may be null</p>
</BODY>
</HTML>
